### PR TITLE
refactor: improved readability in parsetContent()

### LINKED ISSUE #14: Reduce complexity when parsing content
The complexity of the code was increased with #13 by the multiple branching if 

The parsing of the content could be moved out the main with something like this

```go

contentStr, err := parseContent(flag)
if err != nil {
fmt.Println
os.Exitt(1)
}

// …

func parseContent(flag) string, error {
   if directText != {
      return *directText
   }

   // …
}
```

_Originally posted by @ccoVeille in https://github.com/supitsdu/clipper/pull/13#discussion_r1649901636_

### PR DESCRIPTION
**Pull request by supitsdu**
Implement changes [reviewed here](https://github.com/supitsdu/clipper/pull/15#discussion_r1651153541)

- Handle each case in parseContent separately for clarity.
- Integrate the updated parseContent into the main.go.
- Ensure consistent error handling and function documentation.

Closes #14

### CODE REVIEW

**Comment by ccoVeille** [comment]
This PR completes the changes made with #15 for #14

**Review by ccoVeille — APPROVED** [review]

**Comment by karimalzalek** [comment]
Hello @supitsdu and @ccoVeille , looks simpler now, sorry for missing the review.

**Comment by ccoVeille** [comment]
My bad also, so no problem

**Comment by supitsdu** [comment]
> Hello @supitsdu and @ccoVeille , looks simpler now, sorry for missing the review.

Don't worry mate, it was my bad. I should've seen the review made by @ccoVeille. Thank you both for the contributions!

**Pull request merged**
